package ExceptionHandlingDay6;

public class ExceptionDemo2 {

	public static void main(String[] args) {
		
		System.out.println("Program task begins..");
		int a=Integer.parseInt(args[0]);
		int b=Integer.parseInt(args[1]);
		int data[]= {a,b};
		System.out.println("Program task completed..");
		
	}
}
