package ExceptionHandlingDay6;

public class ExceptionDemo1 {

	public static void main(String[] args) {
		
		System.out.println("Program task begins..");
		int a=10;
		int b=0;
		try
		{
			int c=a/b;
			System.out.println(c);
		}catch(ArithmeticException e) {
			
			System.out.println("Cannot divide by zero");
		}
		System.out.println("Program completed task.");

	}

}
